
# {{{ health checkers
### profiles - users - auth
GET http://localhost:8001/health

GET http://localhost:8002/health

GET http://localhost:8003/health

### fmc
GET http://localhost:8005/health

### questions - answers
GET http://localhost:8011/health

GET http://localhost:8012/health

### modules
GET http://localhost:8021/health

### resources - papers
GET http://localhost:8031/health

GET http://localhost:8032/health

### local
GET http://localhost:8000/health
# }}}

### auth bypass
GET http://localhost:8003/auth/bypass/1
Accept: application/json

# {{{ message

GET http://localhost:8000/api/v1/messaging/message/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

GET http://localhost:8000/api/v1/messaging/message/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

POST http://localhost:8000/api/v1/messaging/message/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "title": "Título push",
  "body": "Body push",
  "message_type": "success",
  "content": ["1", "2", "3"],
  "data": { "path": "/home" }
}

PUT http://localhost:8000/api/v1/messaging/message/5
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "title": "Título push",
  "body": "Body push",
  "message_type": "warning",
  "content": ["Importante", "❗ ❗ ❗"],
  "data": { "path": "/home" }
}

# }}}

# {{{ tokens

GET http://localhost:8000/api/v1/messaging/token/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

GET http://localhost:8000/api/v1/messaging/token/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

POST http://localhost:8000/api/v1/messaging/token/
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 3,
  "web_token": { "endpoint": "asldkjflksdjf", "expiration": null }
} 
}

PUT http://localhost:8000/api/v1/messaging/token/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 1,
  "fcm_token": "",
  "web_token": {
    "endpoint": "",
    "expirationTime": null,
    "keys": {
      "p256dh": "",
      "auth": ""
    }
  }
}

PUT http://localhost:8000/api/v1/messaging/token/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

{
  "user_id": 1,
  "fcm_token": null,
  "web_token": {
    "endpoint": "",
    "expirationTime": null,
    "keys": {
      "auth": "",
      "p256dh": ""
    }
  }
}

# }}}

# {{{ dispatcher

GET http://localhost:8000/api/v1/messaging/dispatcher/1/user/1
Accept: application/json
Authorization: Bearer 
Content-type: application/json

# }}}
